[project]
authors = ["Nicholas A. Del Grosso <delgrosso.nick@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Day2"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
pyocclient = ">=0.6, <0.7"
ipykernel = ">=6.29.5, <7"
xarray = ">=2025.1.2, <2026"
netcdf4 = ">=1.7.2, <2"
seaborn = ">=0.13.2, <0.14"
pip = ">=25.0.1, <26"
